/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as Vani2RouteImport } from './routes/vani2'
import { Route as VaniHeadlessRouteImport } from './routes/vani-headless'
import { Route as VaniRouteImport } from './routes/vani'
import { Route as McpPlaygroundRouteImport } from './routes/mcp-playground'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as Vani2BenchmarksRouteImport } from './routes/vani2.benchmarks'
import { Route as VaniPlaygroundRouteImport } from './routes/vani.playground'
import { Route as VaniDocsRouteImport } from './routes/vani.docs'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as BlogsTagsTagRouteImport } from './routes/blogs.tags.$tag'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const Vani2Route = Vani2RouteImport.update({
  id: '/vani2',
  path: '/vani2',
  getParentRoute: () => rootRouteImport,
} as any)
const VaniHeadlessRoute = VaniHeadlessRouteImport.update({
  id: '/vani-headless',
  path: '/vani-headless',
  getParentRoute: () => rootRouteImport,
} as any)
const VaniRoute = VaniRouteImport.update({
  id: '/vani',
  path: '/vani',
  getParentRoute: () => rootRouteImport,
} as any)
const McpPlaygroundRoute = McpPlaygroundRouteImport.update({
  id: '/mcp-playground',
  path: '/mcp-playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const Vani2BenchmarksRoute = Vani2BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => Vani2Route,
} as any)
const VaniPlaygroundRoute = VaniPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => VaniRoute,
} as any)
const VaniDocsRoute = VaniDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => VaniRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const BlogsTagsTagRoute = BlogsTagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/chat': typeof ChatRoute
  '/mcp-playground': typeof McpPlaygroundRoute
  '/vani': typeof VaniRouteWithChildren
  '/vani-headless': typeof VaniHeadlessRoute
  '/vani2': typeof Vani2RouteWithChildren
  '/voice': typeof VoiceRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/vani/docs': typeof VaniDocsRoute
  '/vani/playground': typeof VaniPlaygroundRoute
  '/vani2/benchmarks': typeof Vani2BenchmarksRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/tags/$tag': typeof BlogsTagsTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/mcp-playground': typeof McpPlaygroundRoute
  '/vani': typeof VaniRouteWithChildren
  '/vani-headless': typeof VaniHeadlessRoute
  '/vani2': typeof Vani2RouteWithChildren
  '/voice': typeof VoiceRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/vani/docs': typeof VaniDocsRoute
  '/vani/playground': typeof VaniPlaygroundRoute
  '/vani2/benchmarks': typeof Vani2BenchmarksRoute
  '/blogs': typeof BlogsIndexRoute
  '/blogs/tags/$tag': typeof BlogsTagsTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/chat': typeof ChatRoute
  '/mcp-playground': typeof McpPlaygroundRoute
  '/vani': typeof VaniRouteWithChildren
  '/vani-headless': typeof VaniHeadlessRoute
  '/vani2': typeof Vani2RouteWithChildren
  '/voice': typeof VoiceRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/vani/docs': typeof VaniDocsRoute
  '/vani/playground': typeof VaniPlaygroundRoute
  '/vani2/benchmarks': typeof Vani2BenchmarksRoute
  '/blogs/': typeof BlogsIndexRoute
  '/blogs/tags/$tag': typeof BlogsTagsTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/chat'
    | '/mcp-playground'
    | '/vani'
    | '/vani-headless'
    | '/vani2'
    | '/voice'
    | '/blogs/$slug'
    | '/vani/docs'
    | '/vani/playground'
    | '/vani2/benchmarks'
    | '/blogs/'
    | '/blogs/tags/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/mcp-playground'
    | '/vani'
    | '/vani-headless'
    | '/vani2'
    | '/voice'
    | '/blogs/$slug'
    | '/vani/docs'
    | '/vani/playground'
    | '/vani2/benchmarks'
    | '/blogs'
    | '/blogs/tags/$tag'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/chat'
    | '/mcp-playground'
    | '/vani'
    | '/vani-headless'
    | '/vani2'
    | '/voice'
    | '/blogs/$slug'
    | '/vani/docs'
    | '/vani/playground'
    | '/vani2/benchmarks'
    | '/blogs/'
    | '/blogs/tags/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ChatRoute: typeof ChatRoute
  McpPlaygroundRoute: typeof McpPlaygroundRoute
  VaniRoute: typeof VaniRouteWithChildren
  VaniHeadlessRoute: typeof VaniHeadlessRoute
  Vani2Route: typeof Vani2RouteWithChildren
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vani2': {
      id: '/vani2'
      path: '/vani2'
      fullPath: '/vani2'
      preLoaderRoute: typeof Vani2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vani-headless': {
      id: '/vani-headless'
      path: '/vani-headless'
      fullPath: '/vani-headless'
      preLoaderRoute: typeof VaniHeadlessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vani': {
      id: '/vani'
      path: '/vani'
      fullPath: '/vani'
      preLoaderRoute: typeof VaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-playground': {
      id: '/mcp-playground'
      path: '/mcp-playground'
      fullPath: '/mcp-playground'
      preLoaderRoute: typeof McpPlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/vani2/benchmarks': {
      id: '/vani2/benchmarks'
      path: '/benchmarks'
      fullPath: '/vani2/benchmarks'
      preLoaderRoute: typeof Vani2BenchmarksRouteImport
      parentRoute: typeof Vani2Route
    }
    '/vani/playground': {
      id: '/vani/playground'
      path: '/playground'
      fullPath: '/vani/playground'
      preLoaderRoute: typeof VaniPlaygroundRouteImport
      parentRoute: typeof VaniRoute
    }
    '/vani/docs': {
      id: '/vani/docs'
      path: '/docs'
      fullPath: '/vani/docs'
      preLoaderRoute: typeof VaniDocsRouteImport
      parentRoute: typeof VaniRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/blogs/tags/$tag': {
      id: '/blogs/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/blogs/tags/$tag'
      preLoaderRoute: typeof BlogsTagsTagRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  BlogsTagsTagRoute: typeof BlogsTagsTagRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  BlogsTagsTagRoute: BlogsTagsTagRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface VaniRouteChildren {
  VaniDocsRoute: typeof VaniDocsRoute
  VaniPlaygroundRoute: typeof VaniPlaygroundRoute
}

const VaniRouteChildren: VaniRouteChildren = {
  VaniDocsRoute: VaniDocsRoute,
  VaniPlaygroundRoute: VaniPlaygroundRoute,
}

const VaniRouteWithChildren = VaniRoute._addFileChildren(VaniRouteChildren)

interface Vani2RouteChildren {
  Vani2BenchmarksRoute: typeof Vani2BenchmarksRoute
}

const Vani2RouteChildren: Vani2RouteChildren = {
  Vani2BenchmarksRoute: Vani2BenchmarksRoute,
}

const Vani2RouteWithChildren = Vani2Route._addFileChildren(Vani2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ChatRoute: ChatRoute,
  McpPlaygroundRoute: McpPlaygroundRoute,
  VaniRoute: VaniRouteWithChildren,
  VaniHeadlessRoute: VaniHeadlessRoute,
  Vani2Route: Vani2RouteWithChildren,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
